version: "2.4"
services:
  alexis-restapi:
    container_name: alexis-restapi
    build: .
    env_file:
      - .env
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
  
  
  
    
    
