version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Create env file
          command: |
            echo $ENV | base64 -d >> .env
            source .env
      - run:
          name: Start containers and verify they're working
          command: |
            set -x
            docker-compose -f docker-compose-circleci.yml config
            docker-compose -f docker-compose-circleci.yml up -d
      - run:
          name: Running tests
          command: |
            docker exec -it alexis-restapi npm test