version: 2.1
jobs:
    run_tests:
        docker:
        - image: circleci/node:10
        - steps:
            - checkout #gitclone
            - run: 
                name: npm i dependenies
                command: |
                    npm i 
            - run: 
                name: pass tests
                command: |
                    docker exec -it alexis-restapi npm test
                       